dist: xenial
sudo: required
language: java

env:
  global:
    - SONATYPE_USERNAME=ph@phloc.com
    - secure: "zZrEwsSkU61eXSGU0NRRak2uav+XwEBLSr8PpckDmMN+84+PjEd0Jkr8sfdQIfMGuAevkLcw3yhpq2dAyTV3fTZekKe9bPaEZcnsx5MqTOtIKDIzccGGLCJBXwWxnW2aoMBi7p8qeIyeUMq/sqq24
3lFgkspRpMfhW+fS/M9KKzUKiHF942RlHNaolNbX2OY+0M3rqss9NKsDwj+/w0zE1KE4WkpHMMLZc1j2FT5yRDhxtjvyja+B+JpDWYNZDcCIsc6V+BT5a5xkLtS7RKxg/Xyp7D2AWF7U6Kt0oFrCtcc9ahz/Hjgi
Du8zCd2CASaob4Zp2Zp1uHwvRaCMkENXPwtQG0QP9nRE30eKapMQejWow/5P+Lnm/kzpAuWaG67ebD4p3lqbhWxWro3XC+5KGYyXXpCY679IaO3Z22ygFEjFmXlOs0qbyzLfWefaWQ7kxYGHTtWIx2e+cBtt5W1J
qiYKXVU7OVjPAHfjDoeOhiez564XmLMxpKAgEHgqtnq2JYhfGMnK1AfP4VMHsixPQMPZQzanQqGpOt0yuaOZnku8NhjQNp9UxodJb+3Dv2NZfPp6eLn66j+8wH0akgSmiJTn64Xgrc/AOAYkvivTFA2VevhibRQM
F/jWz3ksZii0ZdZYZzHcV9zaaexds1QXbLqZVbgWtHKueN2qLK0hQI="

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U
  
cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - master

jobs:
  include:
    - stage: test
      jdk: openjdk8
      script:
        - mvn test -B -P coverage
      after_success:
        - mvn deploy --settings travis-settings.xml -DskipTests=true -B -P travis-deploy
        - bash <(curl -s https://codecov.io/bash)
    - stage: test
      jdk: openjdk11
      script:
        - mvn test -B
    - stage: test
      jdk: openjdk12
      script:
        - mvn test -B
